# Generated by Django 4.1.6 on 2023-02-12 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllOpenCaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.combackbox')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_case', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
